### ISSUE TITLE
Support setting of the Plone site Title

### ISSUE THREAD

**Issue by petri** [collective/collective.recipe.plonesite#12]
Seems like it's not possible using the recipe???

**Comment by gforcada** [comment]
Seems not, but that should not be much of a problem if your policy package has a properties.xml file on profiles/default with the following content:

```
<?xml version="1.0"?>
<site>
 <property name="title">My Title</property>
</site>
```

And probably you want to set that on the policy packages rather than on the recipe, don't you think?

**Comment by petri** [comment]
Thanks for commenting. Given in practice one always wants to set the title, but not that often any site properties, it would be nice if one didn't have to add properties.xml just for that. But you're right, not that much of a problem.

**Comment by claytron** [comment]
This recipe tries to be agnostic about such things, @gforcada is correct. If you really wanted to do this with the current version, you could utilize the `post-extras` option. See the docs for more details.
