### ISSUE TITLE
theme not enabled

### ISSUE THREAD

**Issue by iham** [collective/collective.recipe.plonesite#18]
after installing a plone site using this recipe i get all as i wish, except for the theme. this is not enabled. (talking about plone 5 with a default barceloneta theme)

am i missing a point?

**Comment by pbauer** [comment]
You need to load the theme-profile like this: https://github.com/collective/demo.plone.de/blob/master/local_production.cfg#L68

**Comment by iham** [comment]
you, SIR, saved my day!

danke, phillip!
